#!/usr/bin/env node
/**
 * scope-setup — bootstrap a coworker's local agent-scope wiring.
 *
 * What it does (in order, each step is independently skippable / idempotent):
 *
 *   1. Make sure `.dkg/config.yaml` exists. If not, write one with:
 *        - `node.api: http://localhost:9200`           (the local DKG daemon)
 *        - `node.tokenFile: ~/.dkg/auth.token`         (where `dkg start` puts it)
 *        - `contextGraph: dev-coordination`            (team-wide paranet)
 *        - `agent.uri: urn:dkg:agent:cursor-${user}@${host}` (auto-derived per machine)
 *      The values come from constants below; the agent URI is derived from
 *      `process.env.USER` and `os.hostname()` so each coworker / machine has
 *      a distinct identity without anyone editing YAML by hand.
 *
 *   2. If the daemon is reachable on `node.api`, make sure the
 *      `dev-coordination` paranet exists. If it doesn't, create it via the
 *      daemon's `/api/context-graph/create` endpoint. Daemon down → skip
 *      with a one-line note (creation will happen next run / on demand).
 *
 *   3. Print a short summary (what was created / skipped / already-OK) and
 *      a one-line reminder if the user still needs to start the daemon or
 *      restart Cursor.
 *
 * This script is wired into `pnpm postinstall` and `pnpm scope:setup`. The
 * postinstall path uses `--auto` which suppresses prompts and exits 0 even
 * if the daemon is down — we never want `pnpm install` itself to fail on
 * a coworker's machine just because their daemon isn't up yet.
 *
 * Anything that already exists is left strictly alone — re-running this is
 * safe and produces no output beyond `[scope-setup] nothing to do`.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(__filename), '..');

const CONTEXT_GRAPH_ID = 'dev-coordination';
const CONTEXT_GRAPH_NAME = 'Dev Coordination';
const CONTEXT_GRAPH_DESC =
  'Cross-agent dev task coordination — agent-scope reads `tasks:Task` records here to compute each agent\'s allowed write paths.';
const DAEMON_API = 'http://localhost:9200';
const TOKEN_FILE = '~/.dkg/auth.token';

// `--auto` = postinstall mode: never prompt, never fail-loud. Plain
// invocation = the user ran `pnpm scope:setup` themselves and probably
// wants to see what happened, so we print more.
const AUTO_MODE = process.argv.includes('--auto');

function log(msg) {
  process.stdout.write(`[scope-setup] ${msg}\n`);
}

function warn(msg) {
  process.stderr.write(`[scope-setup] ${msg}\n`);
}

/**
 * Build a stable per-machine agent URI. Falls back gracefully when env
 * is weird (CI, containers, etc) so we never produce a URI containing
 * the literal string "undefined".
 */
function deriveAgentUri() {
  const rawUser = process.env.USER || process.env.USERNAME || 'anon';
  const rawHost = os.hostname() || 'machine';
  const slug = (s) =>
    String(s)
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'x';
  return `urn:dkg:agent:cursor-${slug(rawUser)}-${slug(rawHost)}`;
}

function ensureConfigFile() {
  const dkgDir = path.join(REPO_ROOT, '.dkg');
  const configPath = path.join(dkgDir, 'config.yaml');

  if (fs.existsSync(configPath)) {
    return { created: false, configPath };
  }

  fs.mkdirSync(dkgDir, { recursive: true });

  const agentUri = deriveAgentUri();
  const yaml = `# Auto-generated by scripts/scope-setup.mjs on first install.
# Safe to edit by hand — re-running scope-setup will leave it alone.
# This file is gitignored on purpose; it carries your personal agent URI.

contextGraph: ${CONTEXT_GRAPH_ID}

node:
  api: ${DAEMON_API}
  tokenFile: ${TOKEN_FILE}

agent:
  # Auto-derived from \`${process.env.USER || 'anon'}@${os.hostname()}\` so
  # each coworker / machine has a distinct identity. Override this if you
  # want a different URI (e.g. one per parallel Cursor chat).
  uri: ${agentUri}

capture:
  subGraph: chat
  assertion: chat-log
  privacy: team
`;

  fs.writeFileSync(configPath, yaml, 'utf8');
  return { created: true, configPath, agentUri };
}

/**
 * Read the daemon token from `~/.dkg/auth.token` (the canonical location
 * where `dkg start` writes it). Returns null if the file isn't there yet
 * — that just means the daemon hasn't been started on this machine,
 * which is a soft failure for setup purposes.
 */
function readDaemonToken() {
  const tokenPath = path.join(os.homedir(), '.dkg', 'auth.token');
  try {
    const raw = fs.readFileSync(tokenPath, 'utf8');
    const line = raw.split('\n').find((l) => l.trim() && !l.startsWith('#'));
    return line ? line.trim() : null;
  } catch {
    return null;
  }
}

/**
 * Probe the daemon. Short timeout because this runs from postinstall and
 * we don't want `pnpm install` to hang for 30 seconds on machines where
 * the daemon isn't running.
 */
async function probeDaemon() {
  try {
    const res = await fetch(`${DAEMON_API}/api/agent/identity`, {
      signal: AbortSignal.timeout(1500),
    });
    return res.ok || res.status === 401;
  } catch {
    return false;
  }
}

async function ensureContextGraph(token) {
  const headers = {
    'content-type': 'application/json',
    ...(token ? { authorization: `Bearer ${token}` } : {}),
  };

  let listRes;
  try {
    listRes = await fetch(`${DAEMON_API}/api/context-graph/list`, {
      headers,
      signal: AbortSignal.timeout(2000),
    });
  } catch (err) {
    return { ok: false, reason: `list-failed: ${err.message}` };
  }

  if (listRes.status === 401) {
    return { ok: false, reason: 'unauthorized (no token at ~/.dkg/auth.token)' };
  }
  if (!listRes.ok) {
    return { ok: false, reason: `list http ${listRes.status}` };
  }

  const listJson = await listRes.json().catch(() => ({}));
  const exists = (listJson.contextGraphs || []).some(
    (g) => g.id === CONTEXT_GRAPH_ID,
  );
  if (exists) return { ok: true, alreadyExisted: true };

  let createRes;
  try {
    createRes = await fetch(`${DAEMON_API}/api/context-graph/create`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        id: CONTEXT_GRAPH_ID,
        name: CONTEXT_GRAPH_NAME,
        description: CONTEXT_GRAPH_DESC,
      }),
      signal: AbortSignal.timeout(5000),
    });
  } catch (err) {
    return { ok: false, reason: `create-failed: ${err.message}` };
  }

  if (!createRes.ok) {
    const body = await createRes.text().catch(() => '');
    return {
      ok: false,
      reason: `create http ${createRes.status}: ${body.slice(0, 200)}`,
    };
  }
  return { ok: true, alreadyExisted: false };
}

async function main() {
  const cfgResult = ensureConfigFile();
  if (cfgResult.created) {
    log(`wrote ${path.relative(REPO_ROOT, cfgResult.configPath)} (agent=${cfgResult.agentUri})`);
  } else if (!AUTO_MODE) {
    log(`config already exists at ${path.relative(REPO_ROOT, cfgResult.configPath)} — leaving it alone`);
  }

  const daemonUp = await probeDaemon();
  if (!daemonUp) {
    if (AUTO_MODE) {
      // Stay quiet on postinstall — this is the common path. The MCP
      // server will auto-create the paranet on first connect (see
      // ensureContextGraph in packages/mcp-dkg/src/index.ts), so the
      // user genuinely doesn't need to re-run anything after starting
      // the daemon — they can just open Cursor and chat.
      if (cfgResult.created) {
        log(`daemon not reachable yet — fine, the MCP server will create "${CONTEXT_GRAPH_ID}" on its first connect after \`dkg start\`.`);
      }
    } else {
      warn(`daemon not reachable at ${DAEMON_API} — start it with \`dkg start\` and re-run, OR just chat in Cursor (the MCP auto-creates "${CONTEXT_GRAPH_ID}" on first connect).`);
    }
    return 0;
  }

  const token = readDaemonToken();
  const cgResult = await ensureContextGraph(token);
  if (cgResult.ok) {
    if (cgResult.alreadyExisted) {
      if (!AUTO_MODE) log(`context graph "${CONTEXT_GRAPH_ID}" already exists — nothing to do.`);
    } else {
      log(`created context graph "${CONTEXT_GRAPH_ID}" on the local daemon.`);
    }
  } else {
    warn(`could not ensure context graph "${CONTEXT_GRAPH_ID}": ${cgResult.reason}`);
    warn('you can create it later with: dkg paranet create dev-coordination -n "Dev Coordination"');
  }

  if (cfgResult.created && !AUTO_MODE) {
    log('done. Restart Cursor (or any open IDE chats) so the new MCP config picks up.');
  }
  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((err) => {
    if (AUTO_MODE) {
      // Don't break `pnpm install` if something goes sideways
      warn(`postinstall scope-setup failed (non-fatal): ${err?.message || err}`);
      process.exit(0);
    }
    warn(`fatal: ${err?.stack || err}`);
    process.exit(1);
  });
